### ISSUE TITLE
Cannot open copy of mindmap file

### ISSUE THREAD

**Issue by nguyenhung** [ACTom/files_mindmap#48]
NextCloud won't open copy of .km file, it downloads the file instead.

NextCloud: 16.0.0
Mindmap: 0.0.13

Related problem:
#21
#40
#46

**Comment by enca-pl** [comment]
I have the same problem

**Comment by Phenex1978** [comment]
Same problem here with Nexcloud 15.0.7 - Mind Map 0.0.13

If I download a .km file then upload it again, I can not read it with Mind Map anymore

**Comment by nguyenhung** [comment]
#46

**Comment by AndyMephisto** [comment]
same problem

**Comment by vae-0118** [comment]
我也有同样的问题；另外，如果该KM文件在本地编辑过，也无法再次用Mind Map编辑了，而是直接下载。

**Comment by tt33tt** [comment]
Same problem

**Comment by tt33tt** [comment]
I have seen in the source code that normally the app kann deal with xmind files, too. This works not, too. :-)

**Comment by sebelk** [comment]
Same problem here :(

**Comment by Gery1337** [comment]
the problem was solved?

**Comment by enca-pl** [comment]
After implemented changes from fix bug #46 #48 new files works great, sharing with other users also. In case of the earlier file - I copied content from old file to newly created and this one is also working.
Thank You **ACTom** ! Regards

**Comment by Babene03** [comment]
@enca-pl  That are great news

@ACTom Can you create a new release with fix bug #46 #48?

**Comment by ACTom** [comment]
Fixed in v0.0.14.
Try to run `occ files:scan` to fix old files.

**Comment by iacsvrn** [comment]
Problem not solved. if I do right-click select copy - I have a broken file.
Nextcloud: 16.0.3
Mindmap: 0.0.15

---
![image](https://user-images.githubusercontent.com/9478743/63669638-3740ad80-c7e3-11e9-8568-4e827fee0bf4.png)
---

---
![image](https://user-images.githubusercontent.com/9478743/63669714-6b1bd300-c7e3-11e9-8bc6-1449fc8f103f.png)
---

**Comment by Michael2222** [comment]
Hi,

I have the same problem with nc 18.0.3 and mindmap 0.0.21
Have any a solution?

**Comment by Michael2222** [comment]
Hello,
how can I open this ticket again?

**Comment by Michael2222** [comment]
Hello @ACTom 
why do you close this issue, when it is not solved?
Regards
  Michael

**Comment by k-0** [comment]
Same problem here...
Nextcloud 18.0.4 and Mind Map 0.0.21
