### ISSUE TITLE
Mind Map breaks Activity Stream

### ISSUE THREAD

**Issue by glOOmyART** [ACTom/files_mindmap#84]
NC: 18.0.0
PHP: 7.2.27

When MindMap App is active it breaks the activity stream for all users who have a .mk file in their file repository. The activity stream just has the spinning icon on forever.
As soon as I deactivate MindMap App everything works as expected.

The log shows:

> Exception: substr() expects parameter 3 to be integer, boolean given

`lib/private/Files/Type/Detection.php - line 377:
substr("mindmap", 0, false)`

0. public_html/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity\Controller\APIv2 {}, "getFilter")
1. public_html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("APIv2Controller", "getFilter", OC\AppFramework\ ... {}, {filter: "all",_ ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({filter: "all",_ ... "})
3. public_html/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {filter: "all",_ ... "})
4. public_html/ocs/v1.php line 82
   OC\Route\Router->match("/ocsapp/apps/ac ... l")
5. public_html/ocs/v2.php line 24
   require_once("/srv/www/virtua ... p")

GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0

**Comment by Alexconquer** [comment]
Hello, same problem.

NC: 18.0.1
PHP : 7.3.15

**Comment by nickvergessen** [comment]
Fixed by https://github.com/ACTom/files_mindmap/commit/ad802f6186f9f531de927eb82f49818492e3dc10

**Comment by glOOmyART** [comment]
thanks!

**Comment by ACTom** [comment]
Fixed in v0.0.18

**Comment by chrisjq** [comment]
Still doesn't work in 0.0.18 and Mind Map fully broken and now get an error on disabling, reenabling and uninstall. I can't reinstall it now get the following error:
{appId: "files_mindmap", error: TypeError: Cannot read property 'message' of undefined
    at https://<domain>/cloud/apps…}

**Comment by ACTom** [comment]
@chrisjq see #73

**Comment by scroom** [comment]
@ACTom Mind Map-App breaks again my Activity Stream. I'm using 0.0.20 on Nextcloud 18.0.2.

**Comment by scroom** [comment]
Seems to problem just for the users which already used the Mind map app. For all other users the Activity Stream is working just to the moment when they create a mindmap.

**Comment by scroom** [comment]
Error | no app in context | **Exception:** substr() expects parameter 3 to be integer, boolean given 

0. /var/www/nextcloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity ... {}, "getFilter")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("APIv2Controller", "getFilter", OC\AppFramew ... {}, { filter: "a ... "})
2. <<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ filter: "a ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { filter: "a ... "})
4. /var/www/nextcloud/ocs/v1.php - line 82: OC\Route\Router->match("/ocsapp/app ... l")
5. /var/www/nextcloud/ocs/v2.php - line 24: require_once("/var/www/nextcloud/ocs/v1.php")

> Verursacht durchTypeError: substr() expects parameter 3 to be integer, boolean given

0. /var/www/nextcloud/lib/private/Files/Type/Detection.php - line 377: substr("mindmap", 0, false)
1. /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php - line 408: OC\Files\Type\Detection->mimeTypeIcon("mindmap")
2. /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php - line 399: OCA\Activity\Controller\APIv2->getPreviewPathFromMimeType("application/km")
3. /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php - line 356: OCA\Activity\Controller\APIv2->getPreviewFromPath(723086, "/test.km", { path: "/te ... "})
4. /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php - line 304: OCA\Activity\Controller\APIv2->getPreview("tester3", 723086, "/test.km")
5. /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php - line 209: OCA\Activity\Controller\APIv2->get("all", 0, 50, true, "", 0, "desc")
6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\Activity\Controller\APIv2->getFilter("all", 0, 50, true, "", 0, "desc")
7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Activity ... {}, "getFilter")
8. /var/www/nextcloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity ... {}, "getFilter")
9. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("APIv2Controller", "getFilter", OC\AppFramew ... {}, { filter: "a ... "})
10. <<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ filter: "a ... "})
11. /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { filter: "a ... "})
12. /var/www/nextcloud/ocs/v1.php - line 82: OC\Route\Router->match("/ocsapp/app ... l")
13. /var/www/nextcloud/ocs/v2.php - line 24: require_once("/var/www/nextcloud/ocs/v1.php")
-- | -- | --

**Comment by ACTom** [comment]
@scroom https://github.com/ACTom/files_mindmap/issues/99#issuecomment-600412113

**Comment by scroom** [comment]
@ACTom This solved the issue for me. But today I've updated my Nextcloud from 18.0.2 to 18.0.3 and experienced the same again.

**Comment by ACTom** [comment]
@scroom At present, this temporary method can only be used every time. The cause of this problem is that the `news` app introduces symfony components that are not compatible with nextcloud. It can only be completely resolved after the new version of the news app is released.
